### ISSUE TITLE
failed Test_Hello_ReturnsStatus200

### ISSUE THREAD

**Issue by ReDeiPirati** [vfarcic/go-demo#8]
This error is not isolated at Mac OS X system, but even in Debian Linux.
##### Version
```
[Mac OS X]
pirate$ docker --version
Docker version 17.03.1-ce, build c6d412e

pirate$ docker-machine --version
docker-machine version 0.10.0, build 76ed2a6

pirate$ docker-compose --version
docker-compose version 1.11.2, build dfed245

pirate$ uname -a
Darwin pirate-MBP 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

[Debian Linux]
pirate$ docker --version
Docker version 17.03.1-ce, build c6d412e

pirate$ docker-machine --version
docker-machine version 0.10.0 build 76ead2a6

pirate$ uname -a
Linux debian 3.16.0-4 amd64 #1 SMP Debian 3.16.39+deb8u2 (2017-03-07) x86_64 GNU/Linux

```
##### Steps to reproduce the issue:
```
[you can try even within a docker-machine node with virtualbox or pwd driver, the result is the same  ]
pirate$ docker-compose -f docker-compose-test-local.yml  up -d staging-dep
Creating godemo_db_1
Creating godemo_staging-dep_1

pirate$ docker-compose  -f docker-compose-test-local.yml ps
WARNING: The HOST_IP variable is not set. Defaulting to a blank string.
        Name                  Command          State           Ports          
-----------------------------------------------------------------------------
godemo_db_1            /entrypoint.sh mongod   Up      27017/tcp              
godemo_staging-dep_1   go-demo                 Up      0.0.0.0:8080->8080/tcp 

pirate$ docker-compose  -f docker-compose-test-local.yml run --rm staging
WARNING: The HOST_IP variable is not set. Defaulting to a blank string.
Pulling staging (golang:1.6)...
1.6: Pulling from library/golang
....
=== RUN   TestIntegrationTestSuite
=== RUN   Test_Hello_ReturnsStatus200
--- FAIL: Test_Hello_ReturnsStatus200 (20.00s)
        Error Trace:    integration_test.go:48
	Error:      	Received unexpected error:
	            	Get http://staging-dep:8080/demo/hello: dial tcp: lookup staging-dep on 10.0.2.3:53: read udp 10.0.2.15:52485->10.0.2.3:53: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x486092]

goroutine 6 [running]:
panic(0x8ab9e0, 0xc82000e0b0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
testing.tRunner.func1(0xc82007e120)
	/usr/local/go/src/testing/testing.go:467 +0x192
panic(0x8ab9e0, 0xc82000e0b0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
_/usr/src/myapp.IntegrationTestSuite.Test_Hello_ReturnsStatus200(0xc8201ee560, 0xc8201ee570, 0xc82007e120, 0xc82000a068, 0x10)
	/usr/src/myapp/integration_test.go:49 +0x232
_/usr/src/myapp.(*IntegrationTestSuite).Test_Hello_ReturnsStatus200(0xc8200514d0)
	<autogenerated>:77 +0x98
reflect.Value.call(0x7e5860, 0x93dad8, 0x13, 0x945710, 0x4, 0xc820043f08, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x7e5860, 0x93dad8, 0x13, 0xc820043f08, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/stretchr/testify/suite.Run.func2(0xc82007e120)
	/go/src/github.com/stretchr/testify/suite/suite.go:101 +0x3c9
testing.tRunner(0xc82007e120, 0xc8201f0660)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
exit status 2
FAIL	_/usr/src/myapp	20.013s
```

**Comment by vfarcic** [comment]
Let's go step by step and figure out where the problem is.

Can you confirm that the network was created?

```bash
$ docker-compose -f docker-compose-test-local.yml  up -d staging-dep
Creating network "godemo_default" with the default driver
Creating godemo_db_1
Creating godemo_staging-dep_1
```

I did not see in your logs that `godemo_default` network was created. My guess is that it was created earlier.

Next I'll check whether the go-demo API is accessible.

```bash
$ curl -i "localhost:8080/demo/hello"

HTTP/1.1 200 OK
Date: Mon, 01 May 2017 11:37:44 GMT
Content-Length: 14
Content-Type: text/plain; charset=utf-8

hello, world!
```

Finally, staging tests...

```bash
$ docker-compose  -f docker-compose-test-local.yml run --rm staging
....
--- PASS: TestMainSuite (0.01s)
PASS
ok  	_/usr/src/myapp	0.019s
```

Going back to your issue. The key is `Get http://staging-dep:8080/demo/hello: dial tcp: lookup staging-dep on...` from the tests output. That means that tests could not connect to the application through networking created by Docker Compose (another indication that the problem is somehow related to networking).

We can check the networking manually with:

```bash
$ docker container run -it --network godemo_default alpine sh
# apk add --update drill
# drill staging-dep
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 6722
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; staging-dep.	IN	A

;; ANSWER SECTION:
staging-dep.	600	IN	A	172.18.0.3

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.11
;; WHEN: Mon May  1 11:48:45 2017
;; MSG SIZE  rcvd: 56
```

The above commands created a new container connected to the network created by Docker Compose. Inside the container I installed `drill` that provides DNS information. Finally, I drilled `staging-dep` that is the service that hosts `go-demo` and that is being tested. `drill` responded with `ANSWER: 1` meaning that it could reach the service and output it's IP (`172.18.0.3`).

Can you reproduce all those steps and post the result? That might help narrowing down the cause of the problem.

**Comment by vfarcic** [comment]
I accidentally pressed comment in the middle of writing the previous. Please refresh your screen...

**Comment by ReDeiPirati** [comment]
Yes, the `godemo_default` was created earlier, and i can confirm:
```
pirate$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
123996baa854        bridge              bridge              local
e667b5b47dac     => godemo_default      bridge              local
0109686865ad        host                host                local
7991096f6b11        none                null                local
```  

The curl command give me your same output: the API is accessible.
The staging test produce the same output error as above...
Inside the alpine container:
```
/ # drill staging-dep
Error: error sending query: Could not send or receive, because of network error
```

**Comment by vfarcic** [comment]
If `drill staging-dep` gives an error, there's something wrong with networking. The problem is that I'm not sure what it is.

As a side note, I experienced a similar problem with Docker machines this morning. One service could not access the other even though both belonged to the same network. In my case, the problem was that Docker machines cannot support many networks (at least when running locally). However, that is not your case (even though the symptoms are the same) since you don't have many networks (only godemo_default and those setup with Docker Engine).

At this moment I'm very much confused. Can you try the same commands without Docker Machine. Since you're using Docker for AWS, maybe you can run them directly. Depending on whether it works or not, we'll know whether the problem is with Docker Machine or something else on your laptop.

**Comment by ReDeiPirati** [comment]
I have tried the same command locally in Mac and Debian and i get these results:

- *Both* produce the same error during the staging test;
- curl works fine in Mac, but **not** with Debian(Connection refused);
- drill works fine with Mac, but **not** with Debian(network error);

I am a bit confused...

**Comment by vfarcic** [comment]
It's very hard for me to know what the cause of the problem is since I cannot reproduce it in my cluster. My best guess is that there's something "strange" in your environment but I'm not sure what.

Would you be open to a screen-sharing session? I might spot the problem if I can see your system.

**Comment by ReDeiPirati** [comment]
Absolutely, but you have to be a little patience because i have a terrible
bandwidth upload(less than 1Mb).

**Comment by ReDeiPirati** [comment]
Could you provide your version of docker, docker-machine and docker-compose? Today i've tried even on vmware-fusion driver for Mac, but i've got the same problem. What i've is that every time i was using a Linux enviroment then the network is out. But when i use Docker locally with Mac, the network seems fine for some second, then goes down.

**Comment by vfarcic** [comment]
Here it goes:

```
$ docker version
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
$  docker-compose version
docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
$  docker-machine version
docker-machine version 0.10.0, build 76ed2a6
```

I don't think that your problem is related to version of the software. I've tested it many times since I started working on the book and any version since last summer should work. Moreover, I use the same examples in my workshops. An example would be http://vfarcic.github.io/devops21/workshop.html#/7 (move down from there). That particular example is running in AWS cluster created with Terraform.

Are you sure that nothing "special" in the environments you're trying it? A firewall, for example, can easily mess up with Docker network.

**Comment by ReDeiPirati** [comment]
I've retried using docker(*without compose*) and on my local machine finally it works, but docker-compose is incredibly slow and some times does not work on Mac. On Debian everything goes fine with docker but not with docker-compose. Then i've retried with docker-machine with the virtualbox driver and both docker and docker-compose have failed, more in detail when ran the go-demo container, i've found on the log `"wget: can't connect to remote host (127.0.0.1): Connection refused\n"` inspecting the container. Cannot it resolve the localhost inside the container?

Changing docker-machine driver, for example using pwd, everything goes fine both with docker and docker-compose.

**Comment by vfarcic** [comment]
Docker Compose executed Docker commands using its API. It is the same as if you run `docker`directly excepts that it creates a network that you probably didn't create when you run Docker directly. My best guess is that there is something on your local network that clashes with Docker's networking.

Localhost (for example) works inside a container. It will not resolve it to localhost on your node but localhost inside itself.

The fact that the same thing works with pwd which runs completely unrelated with your laptop/infrastructure/network makes my assumptions that there is indeed something "wrong/clashing" in your environment. Since you tried both on MacOS and Ubuntu, it is not local to the OS. Is there a company firewall or a proxy?

I'm not sure what that something is. I might be able to provide more clues if you could let me a remote access to your system.

**Comment by vfarcic** [comment]
Closing due to inactivity. Please reopen the issue if you'd like to continue the conversation.
